version: '3.1'

services:
  dobby: 
    container_name: dobby
    image: denoland/deno:alpine
    command: 
        - --allow-net 
        - --allow-write
        - --allow-read
        - /app/main.ts
    volumes: 
      - $PWD/src:/app
    ports: 
      - 3333:1993
    environment: 
      SECRET_TOKEN: ""
  db:
    image: mysql:5.7
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_DATABASE: dobby
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - db:/var/lib/mysql

volumes:
  db: